[package]
name = "rlox-vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
fst = "0.4.7"
num-derive = "0.4.2"
num-traits = "0.2.18"
